[project]
name = "shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "fastapi>=0.135.1",
    "httpx>=0.28.1",
    "passlib[bcrypt]>=1.7.4",
    "prometheus-client>=0.24.1",
    "psycopg-binary>=3.3.3",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.22",
    "sqlalchemy>=2.0.48",
    "stripe>=14.4.0",
    "uvicorn[standard]>=0.41.0",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "locust",
    "faker",
    "jinja2"
]

[tool.ruff]
line-length = 110
target-version = "py313"
exclude = [
    "main.py",
    "__init__.py",
    "alembic",
    "migrations",
]

[tool.ruff.lint]
select = [
    "E",   # базовые ошибки Python
    "F",   # реальные ошибки кода
    "I",   # сортировка импортов
    "B",   # потенциальные баги
]
ignore = ["B008"]

[tool.ruff.lint.isort]
known-first-party = ["src"]