"""миграция перед сидингом и тестами

Revision ID: 3ce1615e0767
Revises: b551a59b65d0
Create Date: 2025-12-27 20:39:48.489657

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ce1615e0767'
down_revision: str | Sequence[str] | None = 'b551a59b65d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
