services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: python_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0"
    env_file:
      - ./env/.env.docker

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env/.env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d shop"]
      interval: 5s
      timeout: 5s
      retries: 5

  metrics:
    profiles:
      - "monitoring"
    image: prom/prometheus:latest
    container_name: prometeus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafics:
    profiles:
      - "monitoring"
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - metrics

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: