"""Добавил fts для поиска

Revision ID: 05015c0e3598
Revises: 5dad7b7782e7
Create Date: 2026-03-10 20:07:39.396645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05015c0e3598'
down_revision: Union[str, Sequence[str], None] = '5dad7b7782e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE products 
        ADD COLUMN search_vector tsvector 
        GENERATED ALWAYS AS (
            setweight(to_tsvector('russian', coalesce(name, '')), 'A') ||
            setweight(to_tsvector('russian', coalesce(description, '')), 'B')
        ) STORED;
    """)
    op.create_index(
        'idx_products_search_vector',
        'products',
        ['search_vector'],
        postgresql_using='gin'
    )

def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_search_vector')
    op.drop_column('products', 'search_vector')
    # ### end Alembic commands ###
