"""Создал варианты товаров. Заменил корзину на сущность вместо м2м. Добавил категории и ревью

Revision ID: 0bd08cc80977
Revises: e3257085f2ac
Create Date: 2026-01-26 03:50:11.782952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd08cc80977'
down_revision: Union[str, Sequence[str], None] = 'e3257085f2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reviews_count')
    # ### end Alembic commands ###
