"""изменения для интеграций емейл и платежки

Revision ID: 96fa50dc95c9
Revises: 3ce1615e0767
Create Date: 2026-01-04 02:03:01.038368

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96fa50dc95c9'
down_revision: str | Sequence[str] | None = '3ce1615e0767'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('orders', sa.Column('payment_intent', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email_verified')
    op.drop_column('orders', 'payment_intent')
    op.drop_table('email_tokens')
    # ### end Alembic commands ###
